# Generated by Django 4.2.4 on 2023-08-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("news", "author"), name="unique news and user"
            ),
        ),
    ]
